class AppImages {
  AppImages._();

  static const String onBoarding1 = "assets/images/onboarding1.png";
  static const String indiaFlag = "assets/images/indiaflag.png";
  static const String splash = "assets/images/splash.png";
  static const String studentTribe = "assets/images/student_tribe.png";
  static const String whiteCircle = "assets/images/whitecircle.png";
  static const String redtick = "assets/images/redtick.png";
  static const String camera = "assets/images/camera.png";
  static const String gallery = "assets/images/gallery.png";
  static const String plus = "assets/images/plus.png";
  static const String pencil = "assets/images/pencil.png";
  static const String calendra = "assets/images/calendra.png";
  static const String cross = "assets/images/cross.png";
  static const String cake = "assets/images/cake.png";
  static const String location = "assets/images/location.png";
  static const String phone = "assets/images/phone.png";
  static const String mail = "assets/images/mail.png";
  static const String schoolhat = "assets/images/schoolhat.png";
  static const String work = "assets/images/work.png";
  static const String events = "assets/images/events.png";
  static const String interships = "assets/images/interships.png";
  static const String home = "assets/images/home.png";
  static const String honest = "assets/images/honest.png";
  static const String more = "assets/images/more.png";
  static const String money = "assets/images/money.png";
  static const String money1 = "assets/images/money1.png";
  static const String calendra1 = "assets/images/calendra1.png";
  static const String home1 = "assets/images/home1.png";
  static const String comment = "assets/images/comment.png";
  static const String heart = "assets/images/heart.png";
  static const String share = "assets/images/share.png";
  static const String sort = "assets/images/sort.png";
  static const String filter = "assets/images/filter.png";
  static const String stopwatch = "assets/images/stopwatch.png";
  static const String google = "assets/images/google.png";
  static const String facebook = "assets/images/facebook.png";
  static const String twitter = "assets/images/twitter.png";
  static const String netbanking = "assets/images/netbanking.png";
  static const String mobilewallet = "assets/images/mobilewallet.png";
  static const String stcoins = "assets/images/stcoins.png";
  static const String cards = "assets/images/cards.png";
  static const String upi = "assets/images/upi.png";
  static const String paytm = "assets/images/paytm.png";
  static const String paymentsuccess = "assets/images/paymentsuccess.png";
  static const String paymentfail = "assets/images/paymentfail.png";
  static const String location2 = "assets/images/location2.png";
  static const String camera1 = "assets/images/camera1.png";
  static const String avatar = "assets/images/avatar.png";
  static const String comment2 = "assets/images/comment2.png";

  static const String myprofile = "assets/images/myprofile.png";
  static const String stblack = "assets/images/stblack.png";
  static const String appliedInternship = "assets/images/appliedInternship.png";
  static const String bookmark = "assets/images/bookmark.png";
  static const String calendra3 = "assets/images/calendra3.png";
  static const String privacy = "assets/images/privacy.png";
  static const String terms = "assets/images/terms.png";
  static const String refer = "assets/images/refer.png";
  static const String logout = "assets/images/logout.png";

  static const String stsolid = "assets/images/stsolid.png";
  static const String coinbg = "assets/images/coinbg.png";
  static const String rupee = "assets/images/rupee.png";

  static const String second = "assets/images/second.png";
  static const String first = "assets/images/first.png";
  static const String third = "assets/images/third.png";
  static const String arrow = "assets/images/arrow.png";
  static const String bigrupee = "assets/images/bigrupee.png";
  static const String bigcoinbg = "assets/images/bigcoinbg.png";
  static const String crown = "assets/images/crown.png";
  static const String razorpayicon = "assets/images/razorpayicon.png";
}
